### PR TITLE
Added CMake Support

### PR DESCRIPTION
**Pull request by darren-harton**
**Describe the changes**

I added basic CMake support so that other projects may use CMake's `externalproject_add` and `find_package` to use this library. Tests are not being built, but that can be added if requested.

**Testing**

* CPU model, architecture, # of cores and threads: i7-9750H, 6 cores, 12 threads
* Operating system: Ubuntu 20.04.5 LTS
* Name and version of C++ compiler: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
* Full command used for compiling, including all compiler flags:

I compiled another project using your header files as dependencies. A sample project can be provided if requested.

**Additional information**
I used CMake 3.16.3

### CODE REVIEW

**Comment by bshoshany** [comment]
Hi @darren-harton, thanks for opening this PR. Sorry it took me so long to reply. I'm currently on hiatus from developing this package, since I'm too busy teaching. However, I plan to release a new version in the summer.

I always hesitate to add too many files to the repository, since this is supposed to be a small and lightweight package. It is already available through vcpkg and Conan, both of which, I believe, support CMake integration. What would be the benefit of adding these two files to the repository itself?

**Comment by maxhlc** [comment]
I would definitely be interested in native CMake support. Sometimes it can be easier to add external dependencies as git submodules, particularly on machines where particular package managers are not available.

**Comment by darren-harton** [comment]
Hi @bshoshany, no worries about the delay. Thanks for providing this library!

The main benefit of this PR is that it simplifies integrating your library into other libraries. For my project, using `externalproject_add` is a convenient way to download, configure, and install portable dependencies without needing to specify, for example, where the public header files are located. I believe this can also be done with vcpkg, but not without either action from the user or complicated dependency handling.

I saw your feedback on a previous PR and tried to minimize the amount of changes here.

**Comment by bshoshany** [comment]
Okay, thanks for the information! I will review the files you added, and will include them in the next release (probably around April or May).

**Comment by klytje** [comment]
What's the status on this issue? I'd love to see CMake support for this nice library as well.

**Comment by bshoshany** [comment]
Hi @klytje, thanks for your comment. In the end what happened is that I found out there's a way to use this library with Cmake without adding any files to the repository, using CPM, as explained in [the documentation](https://github.com/bshoshany/thread-pool#installing-using-cmake-with-cpm). However, if this is not sufficient for your use, please let me know and I will reconsider.

**Pull request closed without merging**
